### ISSUE TITLE
Export to AC3D (.ac) format

### ISSUE THREAD

**Issue by Symbian9** [OpenVSP/OpenVSP#72] opened 2017-01-31 07:58 UTC
Add possibility for export whole model or each part to AC3D (.ac) format, that can include assembly and parts in single file.

- https://www.inivis.com/ac3d/man/ac3dfileformat.html  
- https://sites.google.com/view/ac3dfileformat/home

### References

- https://github.com/NikolaiVChr/Blender-AC3D  
  - http://www.flightgear.org/forums/viewtopic.php?f=18&t=13442
- http://developer.x-plane.com/tools/ac3d-plugin/

### Additionaly

- https://github.com/jcmellado/hangar
- https://github.com/epatel/ac3dreader
- http://code.j3d.org/impl/ac3d_loader.html

**Comment by ramcdona** [comment] 2017-01-31 16:19
What are you trying to accomplish with the AC3D file?  It looks like its uses are very similar to those we try to cover with X3D files.  Have you tried one of those?

This is a well formed issue (though possibly short on background like the above) with lots of great links, but I don't always check the issues here very often.  If you want to discuss a suggestion, most of that activity happens on the Google Group.

**Comment by ramcdona** [comment] 2023-03-12 21:57
The desire for an easy path from OpenVSP to various flight simulation programs is understood.  So far, none of the sponsors that fund OpenVSP development have made it a priority.

If someone from the community wants to work in this direction, I will be happy to help them out.  In the meantime, I'm closing this issue as it doesn't seem to be going anywhere.

As usual, general discussions are best held in the OpenVSP Google Group -- reserving this list as a place for specific bugs with reproducible steps.

**Closed by ramcdona** 2023-03-12 21:57 UTC
